trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  RESOURCEGROUP: 'aro-rg'
  CLUSTER: 'nasharo'
  
steps:
- bash: az --version
  displayName: 'Show Azure CLI version'

- bash: az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject) --use-git-aliases true
  displayName: 'Set default Azure DevOps organization and project'

- bash: az login
  displayName: 'Authenticate'

- bash: az aro delete --resource-group $(RESOURCEGROUP) --name $(CLUSTER) --yes
  displayName: 'Delete cluster'