trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  RESOURCEGROUP: 'aro-rg'
  CLUSTER: 'nasharo'
  
steps:
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: azure-resource-manager
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show
      
- bash: az --version
  displayName: 'Show Azure CLI version'

- bash: az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject) --use-git-aliases true
  displayName: 'Set default Azure DevOps organization and project'

- bash: |
    az login
    az aro delete --resource-group $(RESOURCEGROUP) --name $(CLUSTER) --yes
  env:
    AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
