pool:
  vmImage: 'ubuntu-latest'

variables:
  RESOURCEGROUP: 'aro-rg'
  CLUSTER: 'nasharo'
  
steps:
- bash: az --version
  displayName: 'Show Azure CLI version'

- bash: az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject) --use-git-aliases true
  displayName: 'Set default Azure DevOps organization and project'

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: azure-resource-manager
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
        echo $(RESOURCEGROUP)
        echo $(CLUSTER)
        echo $(Build.Repository.LocalPath)/pull-secret.txt
 #     az aro create \
 #     --resource-group $(RESOURCEGROUP) \
 #     --name $(CLUSTER) \
 #     --vnet aro-vnet \
 #     --master-subnet master-subnet \
 #     --worker-subnet worker-subnet \
 #     --pull-secret @$(Build.Repository.LocalPath)/pull-secret.txt